version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: ./backend
    command: gunicorn envoy.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "3000:80"
  notifier:
    build:
      context: ./ws_backend
    command: gunicorn --bind 0.0.0.0:5000 api:app
    ports:
      - "5000:5000"
    depends_on:
      - frontend
      - backend