# Generated by Django 3.0.6 on 2020-05-25 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(max_length=512)),
            ],
        ),
    ]
